apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8s1-c858"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8s1-c858"
  template:
    metadata:
      labels:
        app: "k8s1-c858"
    spec:
      containers:
        - name: "k8s1-c858"
          image: "stevenr1.azurecr.io/k8s1"
          ports:
          - containerPort: 80